### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jotasaraiva** [ONSV/dist-app#5]
Essa issue é só para falar que o app já está funcionando, caso queira revisar ou corrigir algo. 
Vou abrir mais uma branch para melhorar a UI e testar outras funcionalidades.

**Comment by jotasaraiva** [comment]
Testes para serem feitos:
- [x] Botões requerem upload de um arquivo para funcionar (não devem agir enquanto não há arquivo)
- [x] Botão de calcular aciona animação de carregamento e mostram tabela
- [x] Botões de download fornecem os dados tratados corretamente
- [x] App consegue lidar com arquivos do tamanho necessário
- [x] App consegue lidar com outras amostras de dados do NDSBR
- [x] Único tipo de arquivo suportado é `.gpkg`

**Comment by pabsantos** [comment]
> Testes para serem feitos:
> 
> * [x]  Botões requerem upload de um arquivo para funcionar (não devem agir enquanto não há arquivo)
> * [x]  Botão de calcular aciona animação de carregamento e mostram tabela
> * [x]  Botões de download fornecem os dados tratados corretamente
> * [x]  App consegue lidar com arquivos do tamanho necessário
> * [x]  App consegue lidar com outras amostras de dados do NDSBR
> * [x]  Único tipo de arquivo suportado é `.gpkg`

Fiz o deploy em https://onsv.shinyapps.io/dist-app/ e percebi algumas coisas:

- Os botões de download estão funcionando mesmo sem ter nada para baixar: eles acabam baixando um `html` vazio.
- Sugiro colocar uma animação de load para quando o app tiver exportando o arquivo para download.
- Tive que adicionar `library("markdown")` no app para ele rodar no shinyapps
